name: Reconcile GitHub Issue

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - closed
      - labeled

# This prevents potential race conditions by only allowing this action to handle
# one update at a time for a given issue.
concurrency:
  group: reconcile-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  reconcile-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reconcile Issue
        id: create
        uses: konveyor/github-actions/reconcile-issue@main
        with:
          jiraBaseUrl: https://issues.redhat.com
          jiraToken: ${{ secrets.JIRA_API_TOKEN }}
          jiraProject: MIG
          additionalLabels: community
